import {
  NAMAA_API_CONFIG,
  callGemini,
  jsonResponse,
  publicRouteStatus,
  normalizeHistory,
  optionsResponse,
  readJson,
  safeText,
} from './_api-config.js';

import {
  NAMAA_DEV_SYSTEM_PROMPT,
  buildWebsiteTemplatePrompt,
} from './prompts/index.js';

const SYSTEM_PROMPT = NAMAA_DEV_SYSTEM_PROMPT;


function formatBrief(brief = {}) {
  if (!brief || typeof brief !== 'object') return '';
  const rows = [
    ['Nom', brief.projectName], ['Étape', brief.stage], ['Type', brief.category], ['Branche', brief.branch],
    ['Marché', brief.market], ['Budget', brief.budget], ['Objectif', brief.goal],
    ['Cible', brief.target], ['Offre', brief.offer],
    ['Canaux', Array.isArray(brief.channels) ? brief.channels.join(', ') : brief.channels],
    ['Langue', brief.language],
  ].filter((row) => row[1]);
  return rows.map(([key, value]) => `${key}: ${String(value).replace(/\s+/g, ' ').trim().slice(0, 220)}`).join('\n');
}
function formatTemplate(template = null) {
  if (!template || typeof template !== 'object') return '';
  const sections = Array.isArray(template.sections) ? template.sections.join(', ') : '';
  const cards = Array.isArray(template.cards) ? template.cards.map((card) => Array.isArray(card) ? card.join(': ') : String(card)).join(' | ') : '';
  const faq = Array.isArray(template.faq) ? template.faq.map((item) => Array.isArray(item) ? item.join(' -> ') : String(item)).join(' | ') : '';
  return [
    `Template: ${String(template.label || template.key || 'Namaa template').slice(0, 120)}`,
    `Tone: ${String(template.tone || '').slice(0, 180)}`,
    `Layout: ${String(template.layout || '').slice(0, 180)}`,
    `Accent: ${String(template.accent || '').slice(0, 50)}`,
    `Sections: ${sections.slice(0, 420)}`,
    `Cards: ${cards.slice(0, 520)}`,
    `FAQ: ${faq.slice(0, 420)}`,
  ].filter(Boolean).join('\n');
}
function buildDevPrompt(prompt, brief, template) {
  const briefText = formatBrief(brief);
  const templateText = formatTemplate(template);
  if (!briefText && !templateText) return prompt;
  return `Structured project brief:
${briefText || 'No brief'}

NamaaDev selected template:
${templateText || 'No template'}

User request:
${prompt}

Create the landing page from the structured brief and the selected template. Use the project name, sector, city, budget and goal where relevant. Keep the page visually aligned with the template tone and sections.`;
}

function extractJson(text) {
  const raw = String(text || '').trim();
  try {
    return JSON.parse(raw);
  } catch (error) {
    const match = raw.match(/\{[\s\S]*\}/);
    if (match) {
      try {
        return JSON.parse(match[0]);
      } catch (innerError) {
        return null;
      }
    }
    return null;
  }
}

export async function onRequestOptions() {
  return optionsResponse();
}

export async function onRequestPost(context) {
  const body = await readJson(context.request);
  const prompt = safeText(body.prompt || body.message || body.question, 4000);
  const brief = body.brief && typeof body.brief === 'object' ? body.brief : null;
  const template = body.template && typeof body.template === 'object' ? body.template : null;
  const controlledPrompt = safeText(buildWebsiteTemplatePrompt({ prompt, brief, template }), 6500);

  if (!prompt) {
    return jsonResponse({ ok: false, error: 'Prompt is required.' }, 400);
  }

  const contents = [
    ...normalizeHistory(body.history),
    {
      role: 'user',
      parts: [{ text: controlledPrompt }],
    },
  ];

  const result = await callGemini({
    env: context.env,
    config: NAMAA_API_CONFIG.dev,
    systemInstruction: SYSTEM_PROMPT,
    contents,
  });

  if (!result.ok) {
    return jsonResponse({
      ok: false,
      route: 'namaa-dev',
      connected: false,
      error: 'Namaa Website route is temporarily unavailable.',
    }, result.status || 500);
  }

  const parsed = extractJson(result.text);
  if (!parsed) {
    return jsonResponse({
      ok: true,
      route: 'namaa-dev',
      connected: true,

      answer: result.text,
      files: null,
      parseWarning: 'Gemini did not return valid JSON. Showing text answer only.',
    });
  }

  return jsonResponse({
    ok: true,
    route: 'namaa-dev',
    connected: true,

    answer: parsed.answer || 'Landing page generated by NamaaDev.',
    meta: {
      pageName: parsed.pageName || 'Namaa landing page',
      sector: parsed.sector || 'business',
      city: parsed.city || 'Morocco',
      templateKey: template?.key || parsed.templateKey || '',
      templateLabel: template?.label || parsed.templateLabel || '',
    },
    files: {
      html: String(parsed.html || '').slice(0, 50000),
      css: String(parsed.css || '').slice(0, 30000),
      js: String(parsed.js || '').slice(0, 12000),
    },
  });
}

export async function onRequestGet(context) {
  const config = NAMAA_API_CONFIG.dev;
  const hasSecret = Boolean(context.env?.[config.apiKeyEnv]);
  return jsonResponse(publicRouteStatus('namaa-dev', hasSecret, { service: 'Namaa Website', mode: 'live-preview-only' }));
}
