import {
  NAMAA_API_CONFIG,
  callGemini,
  jsonResponse,
  normalizeHistory,
  optionsResponse,
  readJson,
  safeText,
} from './_api-config.js';

const SYSTEM_PROMPT = `
You are NamaaDev by Elboubakry Abdessamad.
You create simple landing page examples for Moroccan businesses and startups.

Scope:
Only create landing pages, website structure, HTML/CSS/JS examples, copywriting, CTAs, sections and UI ideas for business/startup/marketing projects in Morocco.
If the user asks outside this scope, politely refuse and redirect to landing pages or business projects.

Output requirements:
Return ONLY valid JSON. No markdown fences. No commentary outside JSON.
The JSON must have this exact shape:
{
  "answer": "short explanation for the chat",
  "pageName": "short landing page name",
  "sector": "detected sector",
  "city": "detected city or Morocco",
  "html": "complete body content or full HTML page",
  "css": "CSS only",
  "js": "small JavaScript only, can be empty"
}

Code rules:
Keep code simple, responsive and safe. No external scripts. No tracking code. No API keys. No forms that submit to unknown services.
Use French by default unless the user writes in Darija/Arabic/English.
Landing page sections should include hero, benefits, method/process, trust, FAQ/CTA when relevant.
`;

function formatBrief(brief = {}) {
  if (!brief || typeof brief !== 'object') return '';
  const rows = [
    ['Nom', brief.projectName], ['Étape', brief.stage], ['Type', brief.category], ['Branche', brief.branch],
    ['Marché', brief.market], ['Budget', brief.budget], ['Objectif', brief.goal],
    ['Canaux', Array.isArray(brief.channels) ? brief.channels.join(', ') : brief.channels],
  ].filter((row) => row[1]);
  return rows.map(([key, value]) => `${key}: ${String(value).slice(0, 300)}`).join('\n');
}
function buildDevPrompt(prompt, brief) {
  const briefText = formatBrief(brief);
  if (!briefText) return prompt;
  return `Structured project brief:\n${briefText}\n\nUser request:\n${prompt}\n\nCreate the landing page from the structured brief. Use the project name, sector, city, budget and goal where relevant.`;
}

function extractJson(text) {
  const raw = String(text || '').trim();
  try {
    return JSON.parse(raw);
  } catch (error) {
    const match = raw.match(/\{[\s\S]*\}/);
    if (match) {
      try {
        return JSON.parse(match[0]);
      } catch (innerError) {
        return null;
      }
    }
    return null;
  }
}

export async function onRequestOptions() {
  return optionsResponse();
}

export async function onRequestPost(context) {
  const body = await readJson(context.request);
  const prompt = safeText(body.prompt || body.message || body.question, 4000);
  const brief = body.brief && typeof body.brief === 'object' ? body.brief : null;
  const controlledPrompt = safeText(buildDevPrompt(prompt, brief), 5000);

  if (!prompt) {
    return jsonResponse({ ok: false, error: 'Prompt is required.' }, 400);
  }

  const contents = [
    ...normalizeHistory(body.history),
    {
      role: 'user',
      parts: [{ text: controlledPrompt }],
    },
  ];

  const result = await callGemini({
    env: context.env,
    config: NAMAA_API_CONFIG.dev,
    systemInstruction: SYSTEM_PROMPT,
    contents,
  });

  if (!result.ok) {
    return jsonResponse({
      ok: false,
      route: 'namaa-dev',
      connected: false,
      provider: 'gemini',
      model: result.model,
      error: result.error,
    }, result.status || 500);
  }

  const parsed = extractJson(result.text);
  if (!parsed) {
    return jsonResponse({
      ok: true,
      route: 'namaa-dev',
      connected: true,
      provider: result.provider,
      model: result.model,
      answer: result.text,
      files: null,
      parseWarning: 'Gemini did not return valid JSON. Showing text answer only.',
    });
  }

  return jsonResponse({
    ok: true,
    route: 'namaa-dev',
    connected: true,
    provider: result.provider,
    model: result.model,
    answer: parsed.answer || 'Landing page generated by NamaaDev.',
    meta: {
      pageName: parsed.pageName || 'Namaa landing page',
      sector: parsed.sector || 'business',
      city: parsed.city || 'Morocco',
    },
    files: {
      html: String(parsed.html || '').slice(0, 50000),
      css: String(parsed.css || '').slice(0, 30000),
      js: String(parsed.js || '').slice(0, 12000),
    },
  });
}

export async function onRequestGet(context) {
  const config = NAMAA_API_CONFIG.dev;
  const hasSecret = Boolean(context.env?.[config.apiKeyEnv]);
  const model = context.env?.[config.modelEnv] || config.fallbackModel;
  return jsonResponse({
    ok: true,
    route: 'namaa-dev',
    provider: 'gemini',
    connected: hasSecret,
    expectedSecret: config.apiKeyEnv,
    model,
  });
}
